variable "region" {
  description = "AWS region for environments/prod resources. Must match backend.tf's region."
  type        = string
  default     = "us-east-1"
}

variable "name_prefix" {
  description = "Prefix applied to environments/prod resource names, kept consistent with bootstrap's name_prefix."
  type        = string
  default     = "estanix-wishlist"
}

variable "profile" {
  description = "AWS profile to use for environments/prod resources. Empty string (default) means no override -- ambient credentials are used (required in CI, which has no named local profile)."
  type        = string
  default     = ""
}

# Unlike SESSION_SECRET (machine-generated, ssm.tf), the admin dashboard
# password must be known by a human to log in via /me/login, so it cannot be
# generated by Terraform. No default on purpose -- supply via
# TF_VAR_admin_password or -var at apply time; never commit a value.
variable "admin_password" {
  description = "Plaintext admin dashboard password, stored as SSM SecureString ADMIN_PASSWORD and compared via crypto.timingSafeEqual in lib/session.ts (Phase 4)."
  type        = string
  sensitive   = true
}
